spring.application.name=ecommerce
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce_db
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=3c4ee477-c165-469c-b9f1-6146d4c16dd3
jwt.access-token-expiration=900000
jwt.refresh-token-expiration=604800000